### ISSUE TITLE
Publishing snapshots up to current time... uses a lot of RAM

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/place#1]
1. High resources
The ammount of RAM used only increces. I don't know how or what place is doing but my theory is it is caching the snapshots and has no way of freeing up RAM. (Based on the screenshot showing the task manager the holochain-runner is keeping it)

I just saw that it got up to just above 8 GB RAM then somehow dumped half of it.

![image](https://github.com/lightningrodlabs/place/assets/65631811/063cc378-9b5c-474e-b012-1722caf7ffea)

![image](https://github.com/lightningrodlabs/place/assets/65631811/0a0abd5a-6125-428a-abfe-21ef75d0a59f)

![image](https://github.com/lightningrodlabs/place/assets/65631811/179a01ea-3260-452b-aa9a-ddf410ea38fb)

3. Starts publishing snapshots from - Birthdate: 13/10/2022, 05:54:53 (0/260026)
Perhaps if nothing has been created or used (This is the first time that I installed and ran place) It could check for any old data and then jump through to the current time. instead of publishing snapshots to the curren time.
5. The current number of Published snapshots does not update unless the user refreshes (F5)

![image](https://github.com/lightningrodlabs/place/assets/65631811/d6430dca-1277-4412-9cf9-5d42adb75748)

https://github.com/lightningrodlabs/place/assets/65631811/9411c730-a508-45fd-bbf7-161143d5ac11

Version - v0.1.0
(This also happens on versions v0.2.0 and the we-applet-rc release) - Running it on Debian 12

PC - Edition	Windows 10 Education
Version	21H2
Installed on	‎13/‎07/‎2022
OS build	19044.3448
Experience	Windows Feature Experience Pack 1000.19044.1000.0

Let me know if you need any further information.
Thanks.

**Comment by TechSupport26** [comment]
After 1.5 hrs Place crashed (Specifically the holochain-runner crashed. Place stayed open but was not able to do anything.) This happened after I reloaded. I was able to reopen Place and it has continued to publish snapshots from where it left off.
See the log below.

```typescript
    at Socket.<anonymous> (C:\Users\zeph.thompson\AppData\Local\Programs\place-app\resources\app\node_modules\@lightningrodlabs\electron-holochain\dist\src\holochain.js:119:33)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[10:42:05][error] Error: memory allocation of 2120000 bytes failed

    at Socket.<anonymous> (C:\Users\zeph.thompson\AppData\Local\Programs\place-app\resources\app\node_modules\@lightningrodlabs\electron-holochain\dist\src\holochain.js:119:33)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[10:42:20][warn]  HOLOCHAIN_RUNNER_QUIT event received
```
